apiVersion: 1

datasources:
  - name: InfluxDB3
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8181
    database: sensor_monitoring
    jsonData:
      dbName: sensor_monitoring
      httpMode: GET
      version: InfluxQL
      insecureGrpc: true
      tlsSkipVerify: true
    isDefault: true
    editable: true
