apiVersion: 1

datasources:
  - name: InfluxDB3
    type: influxdb
    access: proxy
    url: http://localhost:8181
    database: ""
    jsonData:
      version: SQL
      dbName: sensor_monitoring
      insecureGrpc: true
      tlsSkipVerify: true
      pdcInjected: false
    isDefault: true
    editable: true
